export const REQUEST_SAVE_RECIPE_TO_DJANGO = 'REQUEST_SAVE_RECIPE_TO_DJANGO'
export const REQUEST_GET_RECIPE_TO_DJANGO = 'REQUEST_GET_RECIPE_TO_DJANGO'
export const CHECK_GET_RECIPE = 'CHECK_GET_RECIPE'