export const REQUEST_SEND_MESSAGE_TO_FASTAPI = 'REQUEST_SEND_MESSAGE_TO_FASTAPI'
export const REQUEST_GET_MESSAGE_FROM_FASTAPI = 'REQUEST_GET_MESSAGE_FROM_FASTAPI'
export const REQUEST_VOICE_TO_FASTAPI = 'REQUEST_VOICE_TO_FASTAPI'
export const REQUEST_GET_VOICE_TO_FASTAPI = 'REQUEST_GET_VOICE_TO_FASTAPI'